<?php
// reports/patient_list.php — Full Patient List PDF
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../reports/pdf_helper.php';

startSecureSession();
$currentUser = getCurrentUser();
if (!$currentUser || !in_array($currentUser['role_name'], ['admin','nurse'], true)) {
    die('Access denied.');
}

$patients = db()->query(
    "SELECT p.*, u.name, u.email,
            (SELECT COUNT(*) FROM vaccinations v WHERE v.patient_id=p.id) AS vacc_count,
            (SELECT MAX(date_given) FROM vaccinations v WHERE v.patient_id=p.id) AS last_vacc
     FROM patients p JOIN users u ON u.id=p.user_id
     ORDER BY u.name ASC"
)->fetchAll();

auditLog('REPORT_GENERATED', 'patients', null, 'Patient list PDF generated');

$rows = '';
foreach ($patients as $i => $p) {
    $bg  = ($i % 2 === 0) ? '' : 'background:#f8f9fa;';
    $age = calculateAge($p['date_of_birth']);
    $lv  = $p['last_vacc'] ? date('M d, Y', strtotime($p['last_vacc'])) : 'Never';
    $vBadge = $p['vacc_count'] > 0
        ? "<span class='badge badge-success'>{$p['vacc_count']} dose(s)</span>"
        : "<span class='badge badge-warning'>Unvaccinated</span>";
    $rows .= "<tr style=\"{$bg}\">
      <td>" . ($i+1) . "</td>
      <td><strong>{$p['patient_code']}</strong></td>
      <td><strong>{$p['name']}</strong><br><small style='color:#888'>{$p['email']}</small></td>
      <td>{$age} yrs</td>
      <td>{$p['gender']}</td>
      <td>{$p['blood_type']}</td>
      <td>{$p['phone']}</td>
      <td>{$vBadge}</td>
      <td>{$lv}</td>
    </tr>";
}
if (!$rows) {
    $rows = '<tr><td colspan="9" style="text-align:center;padding:20px;color:#888">No patients registered.</td></tr>';
}

$total = count($patients);
$vaccinated   = count(array_filter($patients, fn($p) => $p['vacc_count'] > 0));
$unvaccinated = $total - $vaccinated;

$html  = '<!DOCTYPE html><html><head><meta charset="UTF-8">';
$html .= pdfStyles();
$html .= '</head><body>';
$html .= pdfHeader('Patient Registry Report', 'Complete Patient List — Generated ' . date('F d, Y'));

$html .= <<<HTML
<!-- Stat Row -->
<table style="margin-bottom:20px">
  <tr>
    <td style="text-align:center;background:#e7f0ff;border-radius:6px;padding:14px;width:33%">
      <div style="font-size:28px;font-weight:700;color:#0d6efd">{$total}</div>
      <div style="font-size:10px;color:#555">Total Patients</div>
    </td>
    <td width="2%"></td>
    <td style="text-align:center;background:#d1e7dd;border-radius:6px;padding:14px;width:33%">
      <div style="font-size:28px;font-weight:700;color:#198754">{$vaccinated}</div>
      <div style="font-size:10px;color:#555">Vaccinated</div>
    </td>
    <td width="2%"></td>
    <td style="text-align:center;background:#fff3cd;border-radius:6px;padding:14px;width:30%">
      <div style="font-size:28px;font-weight:700;color:#664d03">{$unvaccinated}</div>
      <div style="font-size:10px;color:#555">Unvaccinated</div>
    </td>
  </tr>
</table>

<div class="section-title">Patient Registry</div>
<table>
  <thead>
    <tr>
      <th>#</th>
      <th>Code</th>
      <th>Name / Email</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Blood</th>
      <th>Phone</th>
      <th>Vaccinations</th>
      <th>Last Vaccinated</th>
    </tr>
  </thead>
  <tbody>{$rows}</tbody>
</table>

<div class="footer">
  GuardVAX Hospital System &nbsp;|&nbsp; Patient Registry Report &nbsp;|&nbsp;
  Generated by: {$currentUser['name']} &nbsp;|&nbsp;
HTML;
$html .= date('F d, Y h:i A') . '</div></body></html>';

generatePdf($html, 'GuardVAX_PatientList_' . date('Ymd') . '.pdf');
