<?php
// reports/vaccination_summary.php — Admin Vaccination Summary PDF
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../reports/pdf_helper.php';

startSecureSession();
$currentUser = getCurrentUser();
if (!$currentUser || !in_array($currentUser['role_name'], ['admin','nurse'], true)) {
    die('Access denied.');
}

$dateFrom = $_GET['date_from'] ?? '';
$dateTo   = $_GET['date_to']   ?? date('Y-m-d');

$where  = '1=1';
$params = [];
if ($dateFrom) { $where .= ' AND v.date_given >= ?'; $params[] = $dateFrom; }
if ($dateTo)   { $where .= ' AND v.date_given <= ?'; $params[] = $dateTo; }

// All vaccinations
$stmt = db()->prepare(
    "SELECT v.date_given, p.patient_code, u.name AS patient_name, vk.name AS vaccine_name,
            v.dose_number, v.site, nu.name AS nurse_name
     FROM vaccinations v
     JOIN patients p ON p.id = v.patient_id
     JOIN users u ON u.id = p.user_id
     JOIN vaccines vk ON vk.id = v.vaccine_id
     JOIN users nu ON nu.id = v.administered_by
     WHERE {$where}
     ORDER BY v.date_given DESC, vk.name"
);
$stmt->execute($params);
$vaccinations = $stmt->fetchAll();

// Summary by vaccine
$byVaccine = db()->prepare(
    "SELECT vk.name AS vaccine_name, COUNT(*) AS total_doses,
            COUNT(DISTINCT v.patient_id) AS unique_patients
     FROM vaccinations v JOIN vaccines vk ON vk.id = v.vaccine_id
     WHERE {$where}
     GROUP BY vk.id ORDER BY total_doses DESC"
);
$byVaccine->execute($params);
$summary = $byVaccine->fetchAll();

// By nurse
$byNurse = db()->prepare(
    "SELECT nu.name AS nurse_name, COUNT(*) AS total
     FROM vaccinations v JOIN users nu ON nu.id = v.administered_by
     WHERE {$where}
     GROUP BY nu.id ORDER BY total DESC"
);
$byNurse->execute($params);
$nurseStats = $byNurse->fetchAll();

$totalVacc = count($vaccinations);

auditLog('REPORT_GENERATED', 'vaccinations', null, "Vaccination summary PDF: {$dateFrom} to {$dateTo}");

// ── Build HTML ────────────────────────────────────────────────
$summaryRows = '';
foreach ($summary as $s) {
    $summaryRows .= "<tr><td><strong>{$s['vaccine_name']}</strong></td><td>{$s['total_doses']}</td><td>{$s['unique_patients']}</td></tr>";
}

$nurseRows = '';
foreach ($nurseStats as $n) {
    $nurseRows .= "<tr><td>{$n['nurse_name']}</td><td>{$n['total']}</td></tr>";
}

$vaccRows = '';
foreach ($vaccinations as $i => $v) {
    $bg = ($i % 2 === 0) ? '' : 'background:#f8f9fa;';
    $vaccRows .= "<tr style=\"{$bg}\">
      <td>" . ($i+1) . "</td>
      <td>{$v['date_given']}</td>
      <td><strong>{$v['patient_name']}</strong><br><small style='color:#888'>{$v['patient_code']}</small></td>
      <td>{$v['vaccine_name']}</td>
      <td><span class='badge badge-primary'>Dose {$v['dose_number']}</span></td>
      <td>{$v['site']}</td>
      <td>{$v['nurse_name']}</td>
    </tr>";
}
if (!$vaccRows) {
    $vaccRows = '<tr><td colspan="7" style="text-align:center;padding:20px;color:#888">No records found for the selected period.</td></tr>';
}

$periodLabel = ($dateFrom ? date('M d, Y', strtotime($dateFrom)) : 'All time') . ' — ' . date('M d, Y', strtotime($dateTo));

$html  = '<!DOCTYPE html><html><head><meta charset="UTF-8">';
$html .= pdfStyles();
$html .= '</head><body>';
$html .= pdfHeader('Vaccination Summary Report', $periodLabel);

$html .= <<<HTML
<!-- Total Banner -->
<div style="background:linear-gradient(135deg,#0d6efd,#0a58ca);color:#fff;border-radius:6px;padding:16px 20px;margin-bottom:20px;text-align:center">
  <div style="font-size:36px;font-weight:700">{$totalVacc}</div>
  <div style="font-size:12px;opacity:.9">Total Vaccinations Recorded</div>
  <div style="font-size:10px;opacity:.7;margin-top:4px">Period: {$periodLabel}</div>
</div>

<!-- Summary Tables Side by Side -->
<table style="margin-bottom:20px">
<tr>
  <td width="60%" style="vertical-align:top;padding-right:12px">
    <div class="section-title">By Vaccine Type</div>
    <table>
      <thead><tr><th>Vaccine</th><th>Total Doses</th><th>Unique Patients</th></tr></thead>
      <tbody>{$summaryRows}</tbody>
    </table>
  </td>
  <td width="40%" style="vertical-align:top">
    <div class="section-title">By Nurse</div>
    <table>
      <thead><tr><th>Nurse</th><th>Vaccinations Given</th></tr></thead>
      <tbody>{$nurseRows}</tbody>
    </table>
  </td>
</tr>
</table>

<!-- Detailed Records -->
<div class="section-title">Detailed Vaccination Records</div>
<table>
  <thead>
    <tr>
      <th>#</th>
      <th>Date</th>
      <th>Patient</th>
      <th>Vaccine</th>
      <th>Dose</th>
      <th>Site</th>
      <th>Nurse</th>
    </tr>
  </thead>
  <tbody>
    {$vaccRows}
  </tbody>
</table>

<div class="footer">
  GuardVAX Hospital System &nbsp;|&nbsp; Vaccination Summary Report &nbsp;|&nbsp;
  Generated by: {$currentUser['name']} &nbsp;|&nbsp; 
HTML;
$html .= date('F d, Y h:i A') . '</div></body></html>';

$filename = 'GuardVAX_VaccinationSummary_' . date('Ymd') . '.pdf';
generatePdf($html, $filename);
